name: Semgrep
on: [pull_request]
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    env:
      INPUT_PUBLISHURL: https://semgrep.snowflake.com
    steps:
      - uses: actions/checkout@v1
      - uses: returntocorp/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: 1
